[package]
name = "paramacode/camera-shaker"
version = "1.0.0"
description = "Procedural camera shake for Roblox"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = [
  "src/**",
  "out/**",
  "LICENSE.txt",
  "README.md",
  "wally.toml"
]

exclude = [
  "node_modules/**",
  ".vscode/**",
  "docs/**",
  "*.toml",
  "*.json",
  "*.tgz"
]

[dependencies]
